name: Workflow on push to develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run commands
        run: |
          echo "This runs when a push is made to the develop branch"