name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install
        run: yarn install

      - name: secrets
        run: echo "${{ secrets.TEST }}"

      - name: Variables
        run: echo ${{ vars.TEST }}

      - name: Variables 222
        run: echo "$REPOSITORY_VAR hihihihihihihihihih"
        env:
          REPOSITORY_VAR: ${{ vars.TEST }}

      - name: TEST
        run: echo "Hello"

