name: Check

on:
  pull_request:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Yarn dependenciessss
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
              yarn-

      - name: Install
        run: yarn install
