name: Check

on:
  pull_request:
    branches:
      - develop

jobs:
  php-artisan-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install
        run: yarn install

      - name: Auto merge
        if: github.event_name == 'pull_request'
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
