name: Check

on:
  pull_request:
    branches:
      - develop

jobs:
  php-artisan-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: yarn install

  automerge:
    runs-on: ubuntu-latest
    needs: php-artisan-test
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          label: "automerge"
          delete_branch: false
          merge_method: "squash"
          merge_commit_message: "Merged by automerge-action"
          log: "DEBUG" # or "TRACE"
      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
