name: PHP Artisan Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  php-artisan-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install
        run: yarn install

      - name: Auto-merge on success
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const pr = github.context.payload.pull_request;
            if (pr) {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash' # or 'merge', 'rebase'
              });
            }
